export default {
  name: 'Eric Furspan',
  title: 'Software Engineer',
  email: 'eric.furspan@gmail.com',
  about: [
    "I'm a software engineer with a passion for building type-safe, performant, scalable, and maintainable web applications. " +
      'I enjoy experimenting with new technologies and open source projects and take pride in crafting engaging & intuitive user experiences on the web.',
  ],
  expertise: [
    'Designing, developing, and planning React applications.',
    'Fostering usability, accessibility, and web security.',
    'Enhancing code quality, scalability, and maintainability.',
    'Writing end-to-end & unit tests, maintaining CI/CD pipelines, and automating routine tasks.',
    'Reducing developer friction, implementing best practices, and modernizing legacy codebases.',
    'Debugging, troubleshooting, analytics & performance monitoring, and writing technical documentation.',
  ],
  skills: [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'React-Native',
    'Redux',
    'Node.js',
    'Jest',
    'Python',
    'Webpack',
    'REST APIs',
    'GraphQL',
    'Postgres',
    'MongoDB',
    'Git',
    'AWS',
    'JIRA',
    'Figma',
  ],
  resumeViewUrl:
    'https://docs.google.com/document/d/e/2PACX-1vRFYzxx4MwLb7-eZOtluuLsJn2yi6-IbryPkOfAKq3XjJIdSEfcQdAz_FPs7tpKJz3IVBQuJRLX0W1o/pub?embedded=true',
  resumeDownloadUrl:
    'https://docs.google.com/document/d/1DuTTxyWvfNpXmj2qNrJnrkcUS2x6OG4cKsmsgyuTm-4/export?format=pdf',
  socialLinks: [
    {
      name: 'GitHub',
      url: 'https://github.com/ericfurspan',
      tooltipText: 'github.com/ericfurspan',
    },
    {
      name: 'LinkedIn',
      url: 'https://www.linkedin.com/in/eric-furspan/',
      tooltipText: 'linkedin.com/in/eric-furspan/',
    },
    {
      name: 'StackOverflow',
      url: 'https://stackoverflow.com/users/5792155/eric-furspan?tab=topactivity',
      tooltipText: 'StackOverflow',
    },
    {
      name: 'daily.dev',
      url: 'https://app.daily.dev/ericfurspan',
      tooltipText: 'app.daily.dev/ericfurspan',
      customIcon: true,
    },
  ],
  projects: [
    {
      title: 'Local Hoops | Knicks Map',
      subtitle:
        'Find a court. Get a bucket. Film your bucket. Upload it to the map. A collaboration with the New York Knicks.',
      liveUrl: 'https://www.nba.com/knicks/new-york-hoops',
      sourceUrl: undefined,
      imgUrl: '/knicks-lh-logo.png',
      tools: ['react', 'javascript', 'firebase', 'chakra-ui'],
    },
    {
      title: 'Ticker Lookup',
      subtitle: 'Easily look up key financial data for any stock.',
      liveUrl: 'https://ticker-lookup.netlify.app/.netlify/functions/lookup',
      sourceUrl: 'https://github.com/ericfurspan/ticker-lookup',
      imgUrl: '',
      tools: ['nodejs', 'typescript', 'netlify', 'alphavantage'],
    },
    {
      title: 'Local Hoops iOS',
      subtitle: 'Find basketball courts, anywhere.',
      liveUrl: 'https://apps.apple.com/us/app/local-hoops/id1452756521',
      sourceUrl: 'https://github.com/ericfurspan/Local-Hoops',
      imgUrl: '/local-hoops.svg',
      tools: ['react-native', 'javascript', 'firebase', 'xcode'],
    },
    {
      title: 'Reps for Responders',
      subtitle: 'Giving First Responders a place to feel, heal & thrive.',
      liveUrl: 'https://repsforresponders.org',
      sourceUrl: 'https://github.com/ericfurspan/rfr',
      imgUrl: '/rfr-logo.webp',
      tools: ['react', 'javascript', 'chakra-ui', 'gatsbyjs'],
    },
    {
      title: 'Personal Page',
      subtitle: 'This website.',
      liveUrl: 'https://ericfurspan.com/',
      sourceUrl: 'https://github.com/ericfurspan/portfolio-vite',
      imgUrl: '',
      tools: ['react', 'typescript', 'material-ui', 'vitejs'],
    },
    {
      title: 'US Constitution Quiz',
      subtitle: 'My very first GitHub project.',
      liveUrl: 'https://ericfurspan.github.io/us-constitution-quiz',
      sourceUrl: 'https://github.com/ericfurspan/us-constitution-quiz',
      imgUrl: '',
      tools: ['html', 'css', 'javascript'],
    },
  ],
};
