export default {
  name: 'Eric Furspan',
  title: 'Software Engineer',
  about:
    "I'm Eric Furspan, a New York based software developer. I specialize in frontend development for mobile and web based applications with a focus on usability, performance and scalability.",
  links: [
    { name: 'email', url: 'mailto:eric.furspan@gmail.com' },
    { name: 'github', url: 'https://github.com/ericfurspan' },
    { name: 'linkedin', url: 'https://www.linkedin.com/in/eric-furspan/' },
    { name: 'stackoverflow', url: 'https://stackoverflow.com/users/5792155/eric-furspan' },
    { name: 'codepen', url: 'https://codepen.io/ericfurspan' },
  ],
  skills: [
    'HTML',
    'CSS',
    'JavaScript',
    'TypeScript',
    'React',
    'React-Native',
    'Redux',
    'Node.js',
    'Jest',
    'Python',
    'Webpack',
    'REST APIs',
    'GraphQL',
    'Postgres',
    'MongoDB',
    'Git',
    'AWS',
  ],
  projects: [
    {
      title: 'Local Hoops',
      subtitle: 'Find basketball courts, anywhere.',
      liveUrl: 'https://apps.apple.com/us/app/local-hoops/id1452756521',
      sourceUrl: 'https://github.com/ericfurspan/Local-Hoops',
      imageUrl: '/local-hoops.svg',
      tools: ['react-native', 'xcode', 'firebase'],
    },
    {
      title: 'Local Hoops Map',
      subtitle: '',
      liveUrl: '',
      sourceUrl: '',
      imageUrl:
        'https://cdn.sanity.io/images/vb687n4o/production/d799d870e76a27e388bf24146f4914ce15547acd-1569x1056.svg',
      tools: ['react', 'chakra-ui'],
    },
    {
      title: 'Reps for Responders',
      subtitle: '',
      liveUrl: 'https://repsforresponders.org',
      sourceUrl: '',
      imageUrl: '/rfr.png',
      tools: ['react', 'chakra-ui'],
    },
    // {
    //   title: '',
    //   subtitle: '',
    //   liveUrl: '',
    //   sourceUrl: '',
    //   imageUrl: '',
    //   tools: ['react'],
    // },
  ],
};
